apiVersion: v2
description: "Eosin - a performant Whole Slide Imaging viewer"
name: eosin
version: 0.0.1
maintainers:
  - name: Tom Havlik
    email: thavlik@protonmail.com
    url: https://thavlik.dev
