imagePullSecrets: []

nats:
  url: "nats://nats.nats.svc.cluster.local:4222"
  user: {}
  password: {}

cors:
  accessControlAllowOrigins:
    - https://eosin.ai
    - https://eosin.io

keycloak:
  endpoint: "https://keycloak.example.com"
  realm: eosin
  clientId:
    valueFrom:
      secretKeyRef:
        name: keycloak-cred
        key: clientid
  clientSecret:
    valueFrom:
      secretKeyRef:
        name: keycloak-cred
        key: clientsecret
  admin:
    realm: master
    username:
      valueFrom:
        secretKeyRef:
          name: keycloak-cred
          key: username
    password:
      valueFrom:
        secretKeyRef:
          name: keycloak-cred
          key: password

s3:
  bucket:
    value: camelyon17
  region:
    value: nyc3
  endpoint:
    value: https://nyc3.digitaloceanspaces.com
  accessKeyId: {}
  secretAccessKey: {}

registry: "" # empty string is the same as "docker.io/"

redis:
  username:
    value: ""
  password:
    value: ""
  host:
    value: ""
  port:
    value: ""
  proto:
    value: redis

prometheus:
  enabled: false

postgres:
  host:
    value: ""
  port:
    value: ""
  database:
    value: ""
  username:
    value: ""
  password:
    value: ""
  sslmode:
    value: ""
  ca:
    value: ""

iam:
  image: thavlik/eosin-iam:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"

storage:
  image: docker.io/thavlik/eosin-storage:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  storageSize: 128Gi
  resources:
    limits:
      memory: "256Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  # storageClassName: ""
  cluster:
    enabled: false

frusta:
  image: docker.io/thavlik/eosin-frusta:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests:
      cpu: "100m"

meta:
  image: docker.io/thavlik/eosin-meta:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug

browser:
  image: docker.io/thavlik/eosin-browser:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: warning
  iamPublicEndpoint: https://iam.eosin.ai
  frustaPublicEndpoint: wss://frusta.eosin.ai/ws
  metaPublicEndpoint: https://api.eosin.ai
  resources:
    limits:
      memory: "256Mi"

compiler:
  enabled: true
  image: docker.io/thavlik/eosin-compiler:latest
  imagePullPolicy: Always
  replicas: 2
  logLevel: debug
  streamName: eosin
  consumerName: compiler
  downloadDir: /tmp/eosin/full
  storageSize: 12Gi
  resources:
    limits:
      memory: "3Gi"
    requests:
      memory: "3Gi"
  # storageClassName: ""
  s3: {}  # Falls back to global s3 settings