imagePullSecrets: []

nats:
  url: "nats://nats.nats.svc.cluster.local:4222"
  user: {}
  password: {}

s3:
  bucket:
    value: camelyon17
  region:
    value: nyc3
  endpoint:
    value: https://nyc3.digitaloceanspaces.com
  accessKeyId: {}
  secretAccessKey: {}

registry: "" # empty string is the same as "docker.io/"

redis:
  username:
    value: ""
  password:
    value: ""
  host:
    value: ""
  port:
    value: ""
  proto:
    value: redis

prometheus:
  enabled: false

postgres:
  host:
    value: ""
  port:
    value: ""
  database:
    value: ""
  username:
    value: ""
  password:
    value: ""
  sslmode:
    value: ""
  ca:
    value: ""

storage:
  image: docker.io/thavlik/histion-storage:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  storageSize: 128Gi
  resources:
    limits:
      memory: "256Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  # storageClassName: ""
  cluster:
    enabled: false

frusta:
  image: docker.io/thavlik/histion-frusta:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug

meta:
  image: docker.io/thavlik/histion-meta:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug

browser:
  image: docker.io/thavlik/histion-browser:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: warning
  resources:
    limits:
      memory: "256Mi"

compiler:
  enabled: true
  image: docker.io/thavlik/histion-compiler:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  streamName: histion
  consumerName: compiler
  downloadDir: /tmp/histion/full
  storageSize: 12Gi
  resources:
    limits:
      memory: "6Gi"
    requests:
      memory: "6Gi"
  # storageClassName: ""
  s3: {}  # Falls back to global s3 settings