apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-browser
spec:
  replicas: {{ .Values.browser.replicas}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-browser
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-browser
    spec:
      restartPolicy: Always
      containers:
      - name: browser
        imagePullPolicy: {{ .Values.browser.imagePullPolicy }}
        image: {{ .Values.browser.image }}
    {{- if .Values.browser.resources }}
        resources:
{{ toYaml .Values.browser.resources | indent 10 }}
    {{- end }}
        ports:
        - containerPort: 3000
          name: http
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          name: metrics
{{- end }}
        env:
{{ include "eosin.metrics-env" . | indent 8 }}
        - name: FRUSTA_ENDPOINT
          value: http://{{ .Release.Name }}-frusta
        - name: PUBLIC_FRUSTA_ENDPOINT
          value: {{ .Values.browser.frustaPublicEndpoint | quote }}
        - name: IAM_ENDPOINT
          value: http://{{ .Release.Name }}-iam
        - name: PUBLIC_IAM_ENDPOINT
          value: {{ .Values.browser.iamPublicEndpoint | quote }}
        - name: META_ENDPOINT
          value: http://{{ .Release.Name }}-meta
        - name: PUBLIC_META_ENDPOINT
          value: {{ .Values.browser.metaPublicEndpoint | quote }}
        # Trust X-Forwarded headers from the ingress controller
        - name: PROTOCOL_HEADER
          value: x-forwarded-proto
        - name: HOST_HEADER
          value: x-forwarded-host
        {{- if .Values.browser.origin }}
        - name: ORIGIN
          value: {{ .Values.browser.origin | quote }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-browser
spec:
  selector:
    app: {{ .Release.Name }}-browser
  ports:
    - port: 80
      targetPort: 3000
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-browser
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-browser
  podMetricsEndpoints:
  - port: metrics
{{- end }}