{{- $image := printf "%s%s" .Values.registry .Values.storage.image -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-storage
spec:
  serviceName: {{ .Release.Name }}-storage
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-storage
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-storage
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: storage
        imagePullPolicy: {{ .Values.storage.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.storage.resources }}
        resources:
{{ toYaml .Values.storage.resources | indent 10 }}
    {{- end }}
        command:
          - eosin-storage
          - server
          - --api-port
          - "80"
{{- if .Values.storage.cluster.enabled }}
          - --cluster-port
          - "7000"
{{- end }}
        ports:
        - containerPort: 80
          protocol: TCP
          name: grpc
{{- if .Values.storage.cluster.enabled }}
        - containerPort: 7000
          protocol: TCP
          name: cluster
{{- end }}
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: SERVICE_NAME
          value: storage
        - name: DATA_ROOT
          value: /data
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.storage.logLevel }}
        - name: STORAGE_ENDPOINT
          value: http://{{ .Release.Name }}-storage:80
{{ include "eosin.metrics-env" . | indent 8 }}
{{ include "eosin.nats-env" . | indent 8 }}
      - name: health
        imagePullPolicy: {{ .Values.storage.imagePullPolicy }}
        image: {{ $image }}
        command:
          - eosin-storage
          - health
          - --http-port
          - "8080"
          - --grpc-target
          - "http://127.0.0.1:80"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: health
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
    {{- if .Values.storage.storageClassName }}
      storageClassName: {{ .Values.storage.storageClassName }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.storage.storageSize }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-storage
  podMetricsEndpoints:
  - port: metrics
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    app: {{ .Release.Name }}-storage
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-storage
  ports:
  - name: grpc
    port: 80
